branch-defaults:
  aws:
    environment: prod-env
    group_suffix: null
  master:
    environment: prod-env
global:
  application_name: r_bets_frontend
  default_ec2_keyname: aws-eb
  default_platform: Node.js
  default_region: us-east-1
  profile: null
  sc: git
